### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by cinder92** [mahdit83/advancedPermissionHandler#2]
hello, when im linking your module android studio says

```
Failed to resolve: ir.mtajik.android:advancedPermissionsHandler:1.0.2
```

any idea?

thanks

**Comment by mahdit83** [comment]
Hi there,
First check your gradle is not in offline mode, then check you internet connection or  if it is ok, set Proxy connection to your system and sysnc gradle again.
Let me know the results.

**Comment by mahdit83** [comment]
@cinder92 Is it worked? please update me.

**Comment by behelit** [comment]
If you copied the line from the github page, make sure you add the missing ' at the end

It resolves ok for me
`implementation 'ir.mtajik.android:advancedPermissionsHandler:1.0.2'`

**Comment by mahdit83** [comment]
@behelit thanks for comment
